server:
  port: ${SERVER_PORT:8500}

spring:
  application:
    name: ms-eureka
  zipkin:
    base-url: ${ZIPKIN_SERVER_URL:http://localhost:9411/}

  boot:
    admin:
      client:
        url: ${SPRING_BOOT_ADMIN_SERVER_URL:http://localhost:8508}

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  server:
    eviction-interval-timer-in-ms: 5000
  instance:
    hostname: ${EUREKA_SERVER_HOST:localhost}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://${eureka.instance.hostname}:${server.port}/eureka/}